mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path, include

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('', include('django.contrib.auth.urls')),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	question_text = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')
	
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
	def __str__(self):
		return self.choice_text
	
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default = 0)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from .models import Choice, Question



class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('polls:index')
	else :
		form = UserCreationForm()
	return render(request, 'polls/signup.html', {'form': form})

def home(request):
	return render(request, 'polls/home.html')

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load bootstrap3 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    <meta charset="utf-8">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
  </head>
  <body>
    <header>
        <div class="col-lg-4 col-lg-offset-4">
          <h1>My Site</h1>
          {% if user.is_authenticated %}
            <a href="{% url 'polls:logout' %}">logout</a>
          {% else %}
            <a href="{% url 'polls:login' %}">login</a> / <a href="{% url 'polls:signup' %}">signup</a>
          {% endif %}
          <hr>
        </div>
    </header>
    <main>
      <div class="col-lg-4 col-lg-offset-4">
      {% block content %}
      {% endblock %}
      </div>
    </main>
  </body>
</html>

polls/templates/polls/detail.html
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="col-lg-4 col-lg-offset-4">
	<h1>{{ question.question_text }}</h1>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" >
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
	{% endfor %}
		<input type="submit" value="Vote" />
	</div>
	</form>
</div>

polls/templates/polls/home.html
{% extends 'polls/base.html' %}

{% block content %}

{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

<h2>Welcome, {{ user.username }}!</h2>
{% if latest_question_list %}
    <ul class="list-group">
    {% for question in latest_question_list %}
        <li class="list-group-item"><a href="{% url 'polls:detail' question.id %}" class="list-group-item list-group-item-action">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


<div class="col-lg-4 col-lg-offset-4">
	<div class="list-group">
		<h1>{{ question.question_text }}</h1>

		<ul class="list-group">
		{% for choice in question.choice_set.all %}
		    <li class="list-group-item">{{ choice.choice_text }}<span class="badge badge-primary badge-pill">{{ choice.votes }}</span></li>
		{% endfor %}
		</ul>

		<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
	</div>
</div>

polls/templates/polls/signup.html
{% extends 'polls/base.html' %}

{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<a href="{% url 'polls:login' %}">Already have an account? Login</a>
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    	<button type="submit" class="btn btn-primary">Sign up</button>
	{% endbuttons %}
  </form>
{% endblock %}